#!/bin/bash
out="$1" ; shift
bootsect="$1"
kernel="$2"

mkdir -p "$(dirname "$out")"

function pad() {
    cat "$1" "$2" /dev/zero 2> /dev/null
}

while :; do
    if pad "$bootsect" "$kernel" \
	| dd if='/dev/stdin' of="$out" bs=512 count=128 conv=notrunc 2> /dev/null; then
	break
    fi
done

