#!/bin/bash
src="$1"
entry="$(sed -rn 's/#define\s+KERNEL_START\s+//p' "$src")"

cat <<EOF
OUTPUT_FORMAT("binary")
SECTIONS
{
  . = $entry;
  .text : {
    KERNEL_CODE = .;
    *(.text)
    *(.rodata)
  }
  .data ALIGN(8) : {
    KERNEL_DATA = .;
    *(.data)
  }
  KERNEL_END = .;
  .bss ALIGN(8) : {
    KERNEL_BSS = .;
    *(.bss)
  }
}
EOF
